# fly.toml app configuration file generated for t33n-ang5t on 2023-06-02T11:06:25+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "t33n-ang5t"
primary_region = "lhr"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
