# fly.toml app configuration file generated for t33n-ang5t on 2023-06-01T17:21:29+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "t33n-ang5t"
primary_region = "lhr"

[env]
  COOKIE_SECRET = "mwOkzEhuE6D520EZNyD3kGYl"
  DB_FILE = "/data/db.sqlite"

[[mounts]]
  source = "data"
  destination = "/data"

[[services]]
  internal_port = 8080

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
